### ISSUE TITLE
Check In Container

### ISSUE THREAD

**Issue by Ploysth** [Ploysth/capstone_project#1]
# Value statement - a requirement, not a solution

As a ground stewardess
I need a container with header and text
so that I can see my Check In schedule 

# Description (Design)
 
![Bildschirmfoto 2022-04-27 um 13 34 39](https://user-images.githubusercontent.com/100590395/165509514-4bf10b0f-8c97-4e7c-9f61-ce026397d894.png)

# Acceptance criteria

- [x] Check In as header
- [x] card container 

**text to container:**
- [x] Uhrzeit von
- [x] Uhrzeit bis
- [x] Airline
- [x] Flugnummer
- [x] Destination
- [x] Registration
- [x] Check In Counter

# Task
- [x] create a state for saving initialData and rendering them in the cards
- [ ] testing
- [ ] storybook

**Comment by mbosselmann** [comment]
Hi Ploy,
your user story is really large and I would recommend you to divide this user story in separate user stories and you have parts in your description that you don't need yet and therefore should be coded later. 
In general I would recommend not to start with a form as first user story, but to first render the result of what you want to display in your app as a result with hardcoded testdata. :) And then I would later code the form.

In the following I will list my remarks to specific parts of your user story:

**Value Statement:**
- Your goal describes the structure of your app and that is not what the value statement is supposed to describe. It would be better to put the focus on the goal and reason for the user.
- Suggestion:
**As a** ground stewardess
**I need** to have the possibility to enter specific information about my flights
**to be able to** monitor my flight schedule?
- For the last line I'm not sure about a good reason, but I hope this example helps to understand what I mean :)

An **idea**: In your value statement you describe three sections that you want to have. Maybe this is a good opportunity to separate these parts in three individual user stories for check-in, boarding and break time?

**Description: Design**
- Your design shows parts that you currently don't need and that should be separated in different user stories like the header component and navigation component. 
As an example for the navigation: You currently only have the "Bearbeiten" section. I think you don't need to have the other parts of the navigation yet and therefore you should focus only on the part of your app that represents the functionality that your user story intends. The same for your header.
- In general I would suggest you to use more scribble like wireframes that you can make with excalidraw instead of your figma wireframes as these should show the whole idea of your app, but the description wireframes only the part of the user story you want to code without any further components that you don't need yet.

**Tasks**
- You should also include the tasks storybook and testing as these are part of every component you want to make.

Please don't be disappointed, because of all the remarks I made. The overall idea is really cool you should just think about making smaller pieces to also make it easier for your to handle your project.

If you want to speak about my remarks, feel free to ask me! :)

**Comment by PReichetanz** [comment]
## Acceptance criteria:
- data is displayed correctly (see design above)

## Tasks
- create a state for saving initialData and rendering them in the cards
- see Mareike's suggestion of storybook and testing
