### ISSUE TITLE
Bookmark Check In

### ISSUE THREAD

**Issue by Ploysth** [Ploysth/capstone_project#4]
# Value statement - a requirement, not a solution

As a **user**
I want to **bookmark Check In**
in order to **be able to find them quickly**

# Description (scribble/design/text)

![Bildschirmfoto 2022-04-29 um 12 55 30](https://user-images.githubusercontent.com/100590395/165931605-01ed5781-8959-434f-a75a-44e973783f67.png)

# Acceptance criteria
- [ ] button should toggle with color
- [ ] link at bottom should still be visible
- [ ] empty bookmark page should show screen 3
- [ ] on screen 2: if I remove a bookmark, `Check In` disappears on the screen

# Task
- [ ] create components/`Bookmark`
- [ ] update components/`Card`
- [ ] create components/`Togglelink`
- [ ] write tests
- [ ] add React Router
- [ ] add components in App
- [ ] create empty-state for `Bookmarks`
