### ISSUE TITLE
Add new Check In

### ISSUE THREAD

**Issue by Ploysth** [Ploysth/capstone_project#5]
# Value statement - a requirement, not a solution

As a **user**
I want to **add new Check In**
in order to **see my own Check In schedule**

# Description (scribble/design/text)
![Bildschirmfoto 2022-04-29 um 13 04 20](https://user-images.githubusercontent.com/100590395/165932798-725c5e2e-3714-4ae7-8636-d87ead463c24.png)

# Acceptance criteria
- [x] Form Page has a title "Add a new Check In"
- [x] Link "Add Check In" links to a Form page screen 2
- [x] Link "show all" links back to screen 1
- [x] Form has 7 text inputs: "Uhrzeit von", "Uhrzeit bis", "Airline", "Flugnummer", "Destination", "Registration", "Check In Counter" are required
- [x] Button `Speichern` submit Form
- [x] If Form is submitted, screen 3 (show all Check In) is shown w/ new Check In on top

# Task
- [x] create components/Form
- [ ] create components/ToggleForm
- [ ] write test
- [x] add components to App
